### PR TITLE
added decision history page

### PR DESCRIPTION
**Pull request by Billy2551**
Added decision history page with table of all previous decisions. Individual decisions link to update pages, but update is not fully built yet.

### CODE REVIEW

**Review by j0nnn — COMMENTED** [review]
wait ill look at this soon.

**Comment by Billy2551** [comment]
Fully implemented update decision and view all decision pages. Functionality is fully implemented to use app reader without giving all officers full access to Airtable.

**Comment by j0nnn** [comment]
Horray!

**Comment by j0nnn** [comment]
No more sharing confidential Airtable password

**Review by aleem08 — APPROVED** [review]

**Pull request merged**
